### what is numpy in python
NumPy is a library for the Python programming language, adding support for large,
multi-dimensional arrays and matrices, along with a wide range of high-level mathematical functions to operate
on these arrays.

**Key Features:**

1. **N-Dimensional Arrays**: NumPy allows you to create arrays with any number of dimensions (up to 32). This
makes it easy to represent complex data structures.
2. **Matrix Operations**: NumPy provides an extensive set of functions for matrix operations, such as matrix
multiplication, determinant calculation, and solving linear systems.
3. **Vectorized Operations**: NumPy allows you to perform element-wise operations on entire arrays at once,
making it much faster than using Python's built-in lists and loops.
4. **Integration with Other Libraries**: NumPy is designed to work seamlessly with other popular Python
libraries for scientific computing, such as SciPy, Pandas, and Matplotlib.

**Why Use NumPy?**

1. **Efficient Data Manipulation**: NumPy arrays are much faster than Python lists when working with large
datasets.
2. **Convenient Matrix Operations**: NumPy's matrix operations simplify complex mathematical calculations.
3. **Interoperability with Other Libraries**: NumPy integrates well with other popular scientific computing
libraries, making it a fundamental tool for many data scientists and researchers.

In summary, NumPy is a powerful library that enables efficient manipulation of large numerical arrays and
matrices in Python, making it an essential tool for scientific computing, data analysis, and machine learning.

In [51]:
import  numpy as np

### what is 1 D array?
In NumPy, a **1D array** (also known as a **vector**) is a type of array that has only one dimension or axis.
In other words, it's an array with only one row and one column.

In Python, you can create a 1D array using the `numpy.array()` function, like this:

In [52]:
# Create a 1D array (vector) with 5 elements
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


### what is 2 D Array?
In NumPy, a **2D array** (also known as a **matrix**) is a type of array that has two dimensions or axes: rows
and columns.

In Python, you can create a 2D array using the `numpy.array()` function, like this:

In [53]:
# Create a 2D array (matrix) with 3 rows and 4 columns
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### what is 3D array?
In NumPy, a **3D array** is simply called an **Tensors** with shape **(M, N, P)**, where **M**, **N**, and **P** are integers
representing the number of elements in each dimension.

In [54]:
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### Access vector element

In [55]:
vector

array([1, 2, 3, 4, 5])

In [56]:
# access single element
print(vector[0]) # 1
print(vector[-1]) # 5

1
5


In [57]:
# access multiple elements
print(vector[:]) # Output: [1 2 3 4 5]
print(vector[1:]) # Output: [2 3 4 5]
print(vector[2:-1]) # Output: [3 4]

[1 2 3 4 5]
[2 3 4 5]
[3 4]


### Access Matrix element

In [58]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# access single element
print(matrix[2,0])
print(matrix[-1,-1])
print(matrix[-2,-2])

9
12
7


In [60]:
# access multiple element
print(matrix[0:-1])
print(matrix[1:-1])
print(matrix[:,2])
print(matrix[:,-1])

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]]
[ 3  7 11]
[ 4  8 12]


### Access tensor element

In [61]:
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [62]:
# access single element
print(tensor[1,0,1])
print(tensor[2,0,1])
print(tensor[2,1,1])

6
10
12


In [63]:
# access multiple element
print(tensor[-1:,:])
print(tensor[0:,:])
print(tensor[::2,0,::2])
print(tensor[2,1:,1:])
print(tensor[0,1,:])

[[[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[1]
 [9]]
[[12]]
[3 4]


### Attributes of a NumPy array:

1. **shape**: The shape of the array, which is a tuple representing the dimensions.

Example: `array.shape` -> `(3, 4)` for a 2D array with 3 rows and 4 columns.

2. **size**: The total number of elements in the array.

Example: `array.size` -> `12` for an array with 3x4 shape.

3. **ndim**: The number of dimensions in the array (e.g., 1 for a vector, 2 for a matrix).

Example: `array.ndim` -> `2`.

4. **dtype**: The data type of each element in the array.

Example: `array.dtype` -> `<f8` for an array of floating-point numbers.

5. **itemsize**: The size of each element in bytes.

Example: `array.itemsize` -> `8` for a float64 array (i.e., 8-byte floats).

6. **nbytes**: The total number of bytes occupied by the array.

Example: `array.nbytes` -> `96` for an array with shape `(3, 4)` and dtype `<f8`.



In [64]:
arr = np.array([1,2,3,4,5])

In [65]:
arr.shape

(5,)

In [66]:
matrix.shape

(3, 4)

In [67]:
tensor.shape

(3, 2, 2)

In [68]:
print(arr.size)

5


In [69]:
print(matrix.size)

12


In [70]:
print(tensor.size)

12


In [71]:
arr.ndim

1

In [72]:
matrix.ndim

2

In [73]:
tensor.ndim

3

In [74]:
arr.itemsize

8

In [75]:
matrix.itemsize

8

In [76]:
tensor.itemsize

8

In [77]:
arr.nbytes

40

In [78]:
vector.nbytes

40

In [79]:
tensor.nbytes

96

### How many way to create an array in numpy?
There are several ways to create an array in NumPy. Here are some of the most common methods:

1. **numpy.array()**: This is the most basic way to create a NumPy array from a Python list or other iterable.

2. **numpy.zeros()**: Create an array filled with zeros.

3. **numpy.ones()**: Create an array filled with ones.

4. **numpy.full()**: Create an array filled with a specified value.

5. **numpy.arange()**: Create an array with evenly spaced values.

6. **numpy.linspace()**: Create an array with evenly spaced values over a specified range.

7. **numpy.identity()**: The identity array is a square array with ones on the main diagonal.


In [80]:
# Create array using list
my_list = [1,2,3,4,5,6]
arr = np.array(my_list)
print(arr)

# Create array using tuple
my_tuple = (1,2,3,4,5,6)
arr = np.array(my_tuple)
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [81]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [82]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [83]:
full = np.full((5,5), True)
full

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [84]:
arange = np.arange(0,5,2)
arange

array([0, 2, 4])

In [85]:
license = np.linspace(0,5,5)
license

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [86]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### change data type using astype attribute
**numpy.astype()** : change the data type


In [87]:
array = np.array([1,2,3,4,5])
array = array.astype(np.int8)
array.dtype

dtype('int8')