**What are array operations?**

Array operations refer to various mathematical operations that can be performed
element-wise or vectorially on NumPy arrays. These operations allow you to perform
common calculations like addition, subtraction, multiplication, division,
exponentiation, and more, as well as some specialized operations like sorting,
reshaping, and aggregating.

**Common array operations:**

1. **Element-wise operations**: Perform an operation on each element of the array.
        * Example: `a + b` (addition) or `a * 2` (multiplication by a scalar)
2. **Broadcasting**: Perform an operation on arrays with different shapes, where one
array has a larger shape than the other.
        * Example: `a + [1, 2, 3]` (broadcasting a scalar to match the shape of `a`)
3. **Vectorized operations**: Perform operations that can be applied element-wise or
vectorially on entire arrays.
        * Example: `np.sin(a)` (compute sine values for each element in `a`)

**How to achieve array operations:**

To perform array operations, you can use the following methods:

1. **Use NumPy functions**: Many NumPy functions are designed to work with arrays,
such as:
        * Arithmetic operators (`+`, `-`, `*`, `/`)
        * Mathematical functions (e.g., `sin`, `cos`, `exp`)
        * Statistical functions (e.g., `mean`, `median`, `std`)
2. **Use array methods**: NumPy arrays have several built-in methods that can be
used to perform operations:
        * `a += b` (addition)
        * `a *= 2` (multiplication by a scalar)
        * `np.sort(a)` (sort the elements of `a`)
3. **Use indexing and slicing**: Use NumPy's indexing and slicing capabilities to
access specific parts of an array:
        * `a[1:3]` (get the second and third elements of `a`)
        * `a[:, 1:]` (get all rows and columns except the first)


In [1]:
import numpy as np

arr = np.arange(1,20,dtype=np.int8)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### max/min/sum/prod function
1. **`np.max(arr)`**
Computes the maximum (largest) value in the input array `arr`.
2. **`np.min(arr)`**
Computes the minimum (smallest) value in the input array `arr`.
3. **`np.sum(arr)`**
Computes the sum of all elements in the input array `arr`.
4. **`np.prod(arr)`**
Computes the product (multiplication) of all elements in the input array `arr`.


In [2]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.prod())

19
1
190
121645100408832000


### mean/median/std/var
1. **`np.mean(arr)`**
Computes the arithmetic mean (average) of the elements in the input array `arr`.
2. **`np.median(arr)`**
Computes the median (middle value) of the elements in the input array `arr`.
3. **`np.std(arr)`**
Computes the standard deviation (a measure of volatility) of the elements in the input array `arr`.
4. **`np.var(arr)`**
Computes the variance (a measure of spread) of the elements in the input array `arr`.



In [3]:
print(arr.mean()) #10.0
print(np.median(arr)) #10.0
print(np.std(arr)) #5.477225575051661
print(np.var(arr)) #30.0

10.0
10.0
5.477225575051661
30.0


### Trigonometric functions

In [4]:
a = np.array([1,2,3,-4,5])
print(a)

[ 1  2  3 -4  5]


In [5]:
print(np.sign(a))
print(np.cos(a))
print(np.tan(a))

[ 1  1  1 -1  1]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654 -1.15782128 -3.38051501]


### dot product

In [6]:
a = np.random.random(10)
b = np.random.random(10)
print(np.dot(a,b))

2.001595248981208


### log and exponents

In [7]:
a = np.random.random(10)
b = np.random.random(10)
print(np.log(a))
print(np.exp(a))

[-4.30067061 -0.08641826 -0.45351474 -1.67287303 -0.12754999 -1.28366697
 -0.59624062 -0.28199393 -0.06288665 -0.69388431]
[1.01365181 2.50230052 1.88776009 1.20647997 2.41150108 1.31919224
 1.73477672 2.12607651 2.55755036 1.64811395]


### round/floor/ceil

In [8]:
a = np.random.random(10)
print(a)
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[0.33225133 0.6560011  0.93785247 0.95602095 0.6489971  0.00975162
 0.26752498 0.4190788  0.52768324 0.14840718]
[0. 1. 1. 1. 1. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Indexing and Slicing

In [9]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [10]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 5
print(a1[5])

5


In [12]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
#10
print(a2[2,2])

10


In [14]:
#5
print(a3[1,0,1])

5


### Iterating

In [15]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
for a in arr:
    print(a)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [17]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
for a in a2:
    print(a)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [19]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [20]:
for a in a3:
    print(a)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [21]:
for a in np.nditer(arr):
    print(a)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Reshape

In [22]:
reshape = np.arange(8).reshape(2,2,2)
print(reshape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
reshape2 = np.arange(8).reshape(4,2)
print(reshape2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Transpose

In [24]:
transpose = np.array([1,2,3,4,5,6,7,8],dtype=np.int8).reshape(2,4)
print(transpose)
print(np.transpose(transpose))
print(transpose.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Revel

In [25]:
revel = np.arange(12).reshape(2,2,3)
print(revel)
print(np.ravel(revel))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking

In [26]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
#hstack-horizontally stacking
print(np.hstack((a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [28]:
#vstack-Vertically stacking
print(np.vstack((a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Splitting

In [29]:
h_split = np.hsplit(a4,2)
for i,j in enumerate(h_split):
    print(f"Column {i} ")
    print(j)

Column 0 
[[0 1]
 [4 5]
 [8 9]]
Column 1 
[[ 2  3]
 [ 6  7]
 [10 11]]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v_split_arr = np.vsplit(arr, 3)

for i, col in enumerate(v_split_arr):
    print(f"Column {i}:")
    print(col)


Column 0:
[[1 2 3]]
Column 1:
[[4 5 6]]
Column 2:
[[7 8 9]]
