### Numpy array vs list

In [1]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
 c.append(a[i] + b[i])
print(time.time()-start)

4.552371978759766


In [2]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

0.2822256088256836


In [3]:
# memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [4]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

### Advance Indexing

In [9]:
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
print(a[1,1])

5


In [16]:
print(a[-1,2])

22


In [17]:
print(a[1:3,1:3])

[[ 5  6]
 [ 9 10]]


In [19]:
print(a[-2:,0:2])

[[16 17]
 [20 21]]


In [23]:
print(a[-2:,2:])

[[18 19]
 [22 23]]


###  Fancy Indexing

In [25]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [26]:
print(a[[0,4,5]])

[[ 0  1  2  3]
 [16 17 18 19]
 [20 21 22 23]]


In [29]:
print(a[[0,2,4],[0,2,3]])

[ 0 10 19]


### Boolean Indexing

In [35]:
a = np.random.randint(1,100,24).reshape(6,4)
print(a)

[[13 65 34 18]
 [95 70 84 49]
 [17 33  9  8]
 [29 66  6 21]
 [93 10 24 78]
 [58 33 17 59]]


In [37]:
print(a)

[[13 65 34 18]
 [95 70 84 49]
 [17 33  9  8]
 [29 66  6 21]
 [93 10 24 78]
 [58 33 17 59]]


In [43]:
#Even number
print(a [ a % 2 == 0] )

[34 18 70 84  8 66  6 10 24 78 58]


In [41]:
# find out all number greater then 50
print(a[a>50])

[65 95 70 84 66 93 78 58 59]


In [44]:
# find out all number greater then 50 and are even
print(a[(a>50)& (a%2 ==0)])

[70 84 66 78 58]


In [51]:
# find all numbers not divisible by 7
print(a[~(a%7==0)])

[13 65 34 18 95 17 33  9  8 29 66  6 93 10 24 78 58 33 17 59]


### Working with missing value

In [58]:
 nan = np.array([1,2,3,np.nan,4,5,np.nan])
 print(nan)

[ 1.  2.  3. nan  4.  5. nan]


In [59]:
nan[~np.isnan(nan)]

array([1., 2., 3., 4., 5.])