### np.sort
Return a sorted copy of an array

In [1]:
import  numpy as np
a = np.random.randint(0,100,24)
a

array([44, 63, 90,  2, 73, 27, 14, 26, 70, 99, 23, 65, 70, 50, 92, 66, 48,
       53, 18, 69, 17, 52, 47,  4], dtype=int32)

In [3]:
#Acending order
print(np.sort(a))
#decending order
print(np.sort(a)[::-1])

[ 1 13 17 19 20 20 21 29 34 35 36 44 45 63 65 67 71 76 78 92 95 95 96 99]
[99 96 95 95 92 78 76 71 67 65 63 45 44 36 35 34 29 21 20 20 19 17 13  1]


In [4]:
b = np.random.randint(0,100,24).reshape(4,6)

In [5]:
print(b)

[[38  5 55 25  7 42]
 [52 53 10 55 39 35]
 [97  0 51 97 65 90]
 [51  8 67 12  6 25]]


In [6]:
# sort based on row
print(np.sort(b))
# Sort based on colum
print(np.sort(b,axis=0))

[[ 5  7 25 38 42 55]
 [10 35 39 52 53 55]
 [ 0 51 65 90 97 97]
 [ 6  8 12 25 51 67]]
[[38  0 10 12  6 25]
 [51  5 51 25  7 35]
 [52  8 55 55 39 42]
 [97 53 67 97 65 90]]


### np.append
append value at the end of an array and create a new array

In [8]:
a = np.array([1,2,3,4,5])
print(a)
new_arr = np.append(a,10)
print(new_arr)

[1 2 3 4 5]
[ 1  2  3  4  5 10]


### np.concatenate
The `np.concatenate` function is a powerful tool for combining multiple arrays into a single array. It's often
used to stack or concatenate arrays along a particular axis

In [23]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)
print(np.concatenate((c,d)))
print(np.concat((c,d),axis=0))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### np.unique
return the unique elements from an array

In [2]:
a = np.array([1,1,2,3,2,1,4,5,2,4])
np.unique(a)

array([1, 2, 3, 4, 5])