### np.sort
Return a sorted copy of an array

In [1]:
import  numpy as np
a = np.random.randint(0,100,24)
a

array([12, 50, 38, 69, 30,  2, 49, 66, 91, 30, 57, 48, 93, 17,  9, 73, 74,
       69, 23, 19, 37, 25,  9, 84], dtype=int32)

In [2]:
#Acending order
print(np.sort(a))
#decending order
print(np.sort(a)[::-1])

[ 2  9  9 12 17 19 23 25 30 30 37 38 48 49 50 57 66 69 69 73 74 84 91 93]
[93 91 84 74 73 69 69 66 57 50 49 48 38 37 30 30 25 23 19 17 12  9  9  2]


In [3]:
b = np.random.randint(0,100,24).reshape(4,6)

In [4]:
print(b)

[[50 16  2 11 55 47]
 [36  8 96 86 65 35]
 [76 46 26 86 43 83]
 [87 42 99  2 20 81]]


In [5]:
# sort based on row
print(np.sort(b))
# Sort based on colum
print(np.sort(b,axis=0))

[[ 2 11 16 47 50 55]
 [ 8 35 36 65 86 96]
 [26 43 46 76 83 86]
 [ 2 20 42 81 87 99]]
[[36  8  2  2 20 35]
 [50 16 26 11 43 47]
 [76 42 96 86 55 81]
 [87 46 99 86 65 83]]


### np.append
append value at the end of an array and create a new array

In [6]:
a = np.array([1,2,3,4,5])
print(a)
new_arr = np.append(a,10)
print(new_arr)

[1 2 3 4 5]
[ 1  2  3  4  5 10]


### np.concatenate
The `np.concatenate` function is a powerful tool for combining multiple arrays into a single array. It's often
used to stack or concatenate arrays along a particular axis

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)
print(np.concatenate((c,d)))
print(np.concat((c,d),axis=0))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### np.unique
return the unique elements from an array

In [8]:
a = np.array([1,1,2,3,2,1,4,5,2,4])
np.unique(a)

array([1, 2, 3, 4, 5])

### np.expand_dims
Insert a new axis that will appear at the specified position

In [9]:
arr = np.array([1,2,3,4])
expand_dim = np.expand_dims(arr,axis=0)
print(expand_dim)
print(expand_dim.shape)

[[1 2 3 4]]
(1, 4)


### np.where
 Return elements chosen from `x` or `y`, depending on a condition.

In [10]:
arr = np.array([1,2,3,4,5,6])
where = np.where(arr>2,'A','B')
print(where)

['B' 'B' 'A' 'A' 'A' 'A']


### np.argmax
 Return the indices of the maximum values along an axis.

In [11]:
arr = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],[4,5,6]])
max_index = np.argmax(arr)
print(max_index)
print(np.argmax(matrix))

5
5


### np.argmin
 Return the indices of the minium values along an axis.

In [12]:
arr = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3,0],[4,5,6,-1]])
min_index = np.argmin(arr)
print(min_index)
min_index = np.argmin(matrix)
print(min_index)

0
7


### np.cumsum
Return the cumulative sum of the elements along a given axis.

In [13]:
arr = np.array([1,2,3,4,5,6])
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10 15 21]


### np.cumprod
Return the cumulative product of the elements along a given axis.

In [14]:
arr = np.array([1,2,3,4,5,6])
cumprod = np.cumprod(arr)
print(cumprod)

[  1   2   6  24 120 720]


### np.percentile
np.percentile() is used to compute the nth percentile of the array elements along a given axis. It helps in understanding the distribution of data by indicating the value below which a given percentage of observations fall.

In [15]:

# Create an example array
data = np.array([1, 2, 3, 4, 5])

# Calculate the 50th percentile (median)
percentile_50 = np.percentile(data, 50)

print("The 50th percentile (median) of the data is:", percentile_50)

The 50th percentile (median) of the data is: 3.0


### np.histogram()
np.histogram() computes the histogram of a set of data. It returns the counts or densities of values falling into specified bins.

In [16]:

# Create an example array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define bin edges
bins = [0, 2, 4, 6, 8, 10]

# Compute the histogram
counts, bin_edges = np.histogram(data, bins)

print("Counts per bin:", counts)
print("Bin edges:", bin_edges)

Counts per bin: [1 2 2 2 2]
Bin edges: [ 0  2  4  6  8 10]


### np.isin
This function checks whether each element of the input array `a` is present in the test-array `b`.

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,1,2,4])
isin = np.isin(a,b)
print(isin)

[ True  True False  True  True]


### np.flip
reverse the order of array element along specified axis

In [19]:
arr = np.array([1,2,3,4,5])
flip = np.flip(arr)
print(flip)

[5 4 3 2 1]


In [25]:
matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix)
matrix_flip = np.flip(matrix,axis=1)
print(matrix_flip)

[[1 2]
 [3 4]
 [5 6]]
[[2 1]
 [4 3]
 [6 5]]


### np.put
 `np.put(arr, indices, values)` replaces the elements of `arr` at the specified `indices` with
the corresponding values from `values`.

In [34]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
np.put(arr,[0,2],[3,4])
print(arr)

[[1 2]
 [3 4]
 [5 6]]
[[3 2]
 [4 4]
 [5 6]]


### np.delete
`np.delete(arr, indices)` removes the elements at the specified `indices` from the array `arr`

In [36]:
arr = np.array([1,2,3,4,5])
delete = np.delete(arr,[0,2])
print(delete)

[2 4 5]
