In [1]:
from random import randint
import numpy as np

### np.random.randint
Generates random integers from a specified range

In [12]:
a = np.random.randint(1,10,5) # 5 random integers between 1 (inclusive) and 10 (exclusive)
print(a)

[6 5 9 8 3]


### np.random.shuffle
Shuffles the elements of an array in place (modifies the original array)

In [10]:
np.random.shuffle(a) # Output: e.g., [3 1 5 2 4] (random order)
print(a)

[5 3 5 6 4 2]


### np.random.rand
Generates an array of random floats between 0 and 1 from a uniform distribution.

In [11]:
random_array = np.random.rand(3)  # 3 random floats between 0 and 1
print(random_array)  # Output: e.g., [0.123 0.456 0.789]

[0.77950609 0.73885064 0.71099007]


### numpy.random.choice
 Generates a random sample from a given array or range.

In [13]:
choices = np.random.choice([1, 2, 3, 4, 5], size=3)  # Picks 3 random elements from the list
print(choices)  # Output: e.g., [2 5 1]

[5 5 4]
